- name: team rocket
  dittos:
    - name: ditto1
      request:
        url: /api/v1/examples
        method: GET
        headers: 
          Authorization: Bearer token
      response:
        status: 200
        body: |
          {
            "asd": 123
          }
